# Generated by Django 5.1.4 on 2025-01-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(default='personal', help_text='Event Category', max_length=100, verbose_name='Event Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Title', max_length=200, null=True, verbose_name='Title'),
        ),
    ]
