# Generated by Django 5.1.4 on 2025-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_category_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(help_text='User ID', null=True, verbose_name='User ID'),
        ),
    ]
