# Generated by Django 5.1.4 on 2025-01-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='description',
        ),
    ]
